# Generated by Django 5.2.15 on 2026-06-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='分類描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='instruments.category', verbose_name='上層分類')),
            ],
            options={
                'verbose_name': '樂器分類',
                'verbose_name_plural': '樂器分類',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='樂器名稱')),
                ('introduction_md', models.TextField(verbose_name='介紹 Markdown')),
                ('history_md', models.TextField(blank=True, verbose_name='歷史背景 Markdown')),
                ('exploded_view_image', models.CharField(blank=True, max_length=500, verbose_name='樂器拆解圖 URL 或檔案路徑')),
                ('timbre_description', models.TextField(blank=True, verbose_name='音色文字描述')),
                ('listen_link', models.URLField(blank=True, max_length=500, verbose_name='聆聽連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='instruments.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '樂器',
                'verbose_name_plural': '樂器',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='instruments_name_88b41b_idx'), models.Index(fields=['category'], name='instruments_categor_5cd1da_idx'), models.Index(fields=['created_at'], name='instruments_created_9abe66_idx')],
            },
        ),
    ]
