# Generated by Django 5.2.15 on 2026-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='資料來源'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Wikidata ID'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['wikidata_id'], name='instruments_wikidat_9510ef_idx'),
        ),
    ]
