# Generated by Django 5.2.15 on 2026-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_source_url_instrument_wikidata_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='來源地區'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='image_source',
            field=models.CharField(blank=True, max_length=500, verbose_name='圖片來源'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='熱門樂器'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_uncommon',
            field=models.BooleanField(default=False, verbose_name='冷門樂器'),
        ),
    ]
