"""
Popular and uncommon instrument name lists (English lowercase).
These are used to flag instruments as popular or uncommon via
the enrich_instruments management command.

Popular = widely known globally (piano, guitar, violin, etc.)
Uncommon = obscure or lesser-known instruments
"""
import re

POPULAR_INSTRUMENTS = {
    "accordion", "acoustic guitar", "bagpipe", "balalaika", "bandoneon",
    "banjo", "bass drum", "bass guitar", "bassoon", "berimbau",
    "bongo", "bongo drum", "bouzouki", "bugle",
    "cajon", "carillon", "castanets", "cello", "clarinet",
    "classical guitar", "concertina", "conga", "cor anglais",
    "cowbell", "cymbal", "darbuka", "didgeridoo", "djembe",
    "double bass", "drum", "drum kit", "duduk", "electric guitar",
    "english horn", "erhu", "finger cymbal",
    "flute", "french horn", "gamelan", "glockenspiel",
    "gong", "grand piano", "guitar",
    "guzheng", "hammered dulcimer", "handpan", "harmonica",
    "harmonium", "harp", "harpsichord", "koto", "lute",
    "mandolin", "maraca", "marimba", "mouth harp",
    "oboe", "ocarina", "organ", "pan flute", "pan pipes",
    "piano", "piccolo", "pipe organ", "rainstick",
    "recorder", "saxophone", "shamisen", "sheng",
    "sitar", "snare drum", "steel drum", "steelpan",
    "tabla", "taiko", "tambourine", "theremin",
    "timpani", "triangle", "trombone", "trumpet",
    "tuba", "ukulele", "vibraphone", "viola",
    "violin", "xylophone", "yangqin", "zither",
    "dizi", "pipa", "harmonica", "balalaika",
    "castanets", "claves", "cabasa", "guiro",
    "agogo", "vibraslap", "flexatone", "clash cymbals",
    "sleigh bell", "jingle bell", "hi-hat", "crash cymbal",
    "ride cymbal", "splash cymbal", "tom-tom drum",
    "woodblock", "bell", "tubular bells", "chimes",
    "musical saw", "jaw harp", "jew's harp",
    "music box", "handbell", "wind chime",
    "singing bowl", "tibetan singing bowl",
    "djembe", "conga", "bongo", "tabla", "darbuka",
    "doumbek", "timbales", "bodhran", "frame drum",
    "daf", "dayereh", "bendir", "udu",
    "thumb piano", "mbira", "kalimba",
    "bass clarinet", "bass saxophone", "baritone saxophone",
    "alto clarinet", "soprano saxophone", "tenor saxophone",
    "baritone horn", "euphonium", "cornet", "flugelhorn",
    "piccolo trumpet", "bass trombone", "contrabassoon",
    "celesta", "clavichord", "clavinet", "mellotron",
    "synthesizer", "drum machine", "sampler", "electric piano",
    "acoustic bass guitar", "dobro", "resonator guitar",
    "twelve-string guitar", "lap steel", "pedal steel",
    "mandola", "mandocello", "octave mandolin",
    "concert harp", "celtic harp", "folk harp", "lever harp",
    "baroque guitar", "archlute", "theorbo", "santur",
    "cimbalom", "dulcimer", "autoharp", "psaltery",
    "bowed psaltery", "hurdy-gurdy", "nyckelharpa",
    "cajun accordion", "melodeon", "reed organ",
    "harmonium", "sho", "sheng", "khaen", "harmonica",
    "melodica", "accordion", "concertina", "bandoneon",
    "tin whistle", "irish whistle", "low whistle",
    "fife", "piccolo", "bass flute", "alto flute",
    "pan flute", "panpipes", "shakuhachi", "neylegend",
    "kaval", "ney", "duduk", "balaban", "hichiriki",
    "bansuri", "venu", "bawu", "xiao", "dizi", "suling",
    "recorder", "ocarina", "slide whistle", "slide whistle",
    "bullroarer", "wobble board", "whirly tube",
    "kazoo", "mirliton", "comb and paper",
    "vuvuzela", "party horn", "siren", "police whistle",
    "tin horn", "car horn", "train whistle",
    "didgeridoo", "alphorn", "tibetan horn", "dungchen",
    "lur", "bucium", "carnyx", "conch",
    "bagpipe", "uilleann pipes", "northumbrian smallpipes",
    "great highland bagpipe", "gaida", "gaita",
    "cornemuse", "biniou", "dudy", "zampogna",
    "sackbut", "shawm", "dulzaina",
    "crumhorn", "cornett", "serpent", "ophicleide",
    "keyed trumpet", "natural trumpet", "baroque trumpet",
    "saxhorn", "sarrusophone", "heckelphone",
    "lute", "theorbo", "archlute", "chitarra italiana",
    "vihuela", "guitar", "classical guitar",
    "guitarra flamenca", "cavaquinho", "ukulele",
    "mandolin", "mandola", "mandocello", "mandobass",
    "balalaika", "domra", "bandura", "kobza",
    "bouzouki", "baglamas", "tzouras", "cura",
    "tanbur", "saz", "bağlama", "divan saz",
    "setar", "dotar", "dutar", "tamburitza",
    "sitar", "surbahar", "rudra veena", "saraswati veena",
    "tanpura", "swarmandal", "bulbul tarang",
    "shamisen", "biwa", "pipa", "liuqin", "sanxian",
    "koto", "guzheng", "se", "yazheng", "zheng",
    "gayageum", "geomungo", "ajaeng", "daegeum",
    "sog-ak", "hyang-ak", "tang-ak",
    "erhu", "gaohu", "zhonghu", "banhu", "jinghu",
    "yehu", "daguangxian", "tiqin", "morin khuur",
    "igil", "topshur", "kobyz",
    "kamancheh", "kemenche", "rebab", "rebec",
    "cello", "viola", "violin", "double bass",
    "viola da gamba", "viola d'amore", "violone",
    "tromba marina", "trumscheit", "nyckelharpa",
    "ground bow", "musical bow", "berimbau",
    "washtub bass", "diddley bow", "cigar box guitar",
    "guiro", "reco-reco", "güiro", "washboard",
    "vibraslap", "flexatone", "quijada",
    "marimbola", "marimbula", "kalimba", "mbira",
    "likembe", "kisanji", "kouxian", "morsing",
    "vargan", "mouth harp", "jaw harp", "jew's harp",
    "ghatam", "matki", "mrdangam", "khol",
    "pakhawaj", "tabla", "bayan", "dhol", "dholak",
    "nagara", "naqqara", "timpani", "kettle drum",
    "goblet drum", "djembe", "ashiko", "bougarabou",
    "conga", "tumbadora", "bongo", "bongo drum",
    "timbales", "paila", "darbuka", "doumbek",
    "tombak", "zarb", "tonbak", "daf", "dayereh",
    "bendir", "frame drum", "shaman drum",
    "bodhran", "tambourine", "pandeiro", "tamborim",
    "snare drum", "side drum", "field drum",
    "bass drum", "gran cassa", "kick drum",
    "tom-tom", "floor tom", "rototom", "octoban",
    "drum kit", "drum machine",
    "conga", "bongo", "steel drum", "steelpan",
    "vibraphone", "marimba", "xylophone", "glockenspiel",
    "celesta", "orchestral bells", "xylorimba",
    "crotales", "antique cymbals", "finger cymbals",
    "bell lyre", "chimes", "tubular bells",
    "handbells", "bell plate", "cowbell",
    "triangle", "anvil", "brake drum",
    "cymbal", "crash cymbal", "ride cymbal",
    "hi-hat", "splash cymbal", "china cymbal",
    "swish cymbal", "sizzle cymbal", "clash cymbals",
    "gong", "tam-tam", "singing bowl", "wind gong",
    "thunder sheet", "mark tree", "wind chime",
    "agogo", "cabasa", "shekere", "afoxe",
    "rainstick", "claves", "castanets", "maraca",
    "shaker", "egg shaker", "caxixi", "rattle",
    "tambourine", "pandero", "taiko", "wadaiko",
    "slit drum", "teponeztli", "log drum",
    "cajon", "conga box", "tumba",
    "melodica", "harmonica", "accordion", "bandoneon",
    "theremin", "otamatone", "stylophone", "tenori-on",
    "continuum fingerboard", "haken continuum",
}

UNCOMMON_INSTRUMENTS = {
    "3rd bridge", "aeolodion", "aeolsklavier", "agidigbo",
    "agung", "agung a tamlang", "ahardin", "angklung", "arghul",
    "asalato", "atabaque", "babarak", "babendil",
    "balafon", "balkan tambura", "bandura", "bandurria",
    "bar zither", "barbat", "basset clarinet",
    "beena", "begena", "bell tree", "bent drum",
    "bianzhong", "biflute", "bladder fiddle",
    "bock-a-da-bock", "bombard", "bombarde", "bombardon",
    "bougarabou", "bowed psaltery", "buccina", "bucium",
    "bukkehorn", "bulbul tarang", "byzantine lyra",
    "caixa", "cajita", "calliope", "carnyx",
    "cavaquinho", "caxixi", "celempung",
    "chajchas", "chalumeau", "chang", "chapman stick",
    "charango", "ching", "chitarra italiana",
    "citera", "cithara", "clavioline", "cobza",
    "conch shell", "cornamuse", "cornemuse", "cornett",
    "cornu", "cricri", "cristal baschet",
    "cromorne", "crumhorn", "crwth", "cuatro",
    "cuatro venezolano", "cuica", "cumbus", "cura",
    "cylindrical drum", "dabakan", "daguangxian",
    "daxophone", "devil chase", "dhantal",
    "diddley bow", "dilruba", "diple", "divan saz",
    "dombra", "domra", "donso ngoni", "dotar",
    "dranyen", "dulce melos", "dunun", "dutar",
    "duxianqin", "dungchen", "dung dkar", "dvojnice",
    "earth harp", "eigenharp", "ektara",
    "electric pipa", "en小青", "english horn",
    "epinette", "fangxiang", "friction drum",
    "gandingan", "gandingan a kayo", "gangsa",
    "gender", "genggong", "glasschord",
    "glass harmonica", "glass harp", "glass marimba",
    "gogona", "ground bow", "guban",
    "guitarra battente", "guitarron", "gusli",
    "harmoneon", "harp lute", "harpejji",
    "heckelphone", "hichiriki", "hirtenschalmei",
    "hocchiku", "hosho", "hourglass drum",
    "huaca", "huiringua", "hydrodaktulopsychicharmonica",
    "hyoshigi", "ichigenkin", "idiochord", "ikembe",
    "inline chromatic harp", "jap fiddle",
    "jegog", "kacapi", "kaffir piano", "kagul",
    "kaval", "khloy", "khlui", "kisanji",
    "kolintang", "kora", "kouxian", "kse diev",
    "kubing", "kulintang", "kulintang a kayo",
    "kulintang a putao", "kulintang a tiniok",
    "kwintangan kayo", "langeleik", "lesiba",
    "likembe", "lion's roar", "lithophone",
    "liuqin", "long-string instrument", "luntang",
    "malimbe", "mandolute", "marimbaphone",
    "marimbula", "martinshorn", "marxophone",
    "masenqo", "melodica", "metallophone",
    "monochord", "moodswinger",
    "morsing", "mukkuri", "musical bow", "mvet",
    "nail violin", "nyatiti", "oboe d'amore",
    "oboe da caccia", "octobass",
    "onavillu", "oopoochawa", "oud",
    "paiban", "palendag", "panduri", "pandura",
    "pantalon", "pedal harp", "pellet drum",
    "piccolo oboe", "piston flute", "pitch pipe",
    "pluriarc", "pong lang", "portuguese guitar",
    "psalmodicon", "pulalu", "putipu",
    "qanbus", "qanun", "raft zither",
    "ranat ek lek", "ranat thum lek", "ratchet",
    "rattle drum", "rebec", "regal", "reyong",
    "rommelpot", "rubab", "russian guitar",
    "sanshin", "santur", "sanxian",
    "sarrusophone", "sarunay", "scheitholt",
    "seperewa", "shahi baaja", "shime-daiko",
    "shishi-odoshi", "slapstick", "slit drum",
    "soprano sarrusophone", "space harp",
    "spoon", "suikinkutsu", "suling",
    "contrabass sarrusophone", "surbahar",
    "surma-horn", "swarmandal", "tagutok",
    "takuapu", "tamak", "tambourine de bearn",
    "tanbur", "tank drum", "tanpura", "tarogato",
    "temir komuz", "tenor sarrusophone",
    "tenoroon", "teponaztli", "tiorbino",
    "tiqin", "tom", "topshur",
    "toy piano", "tromba marina",
    "trough zither", "tube zither",
    "tumbi", "tumdak", "tumpong",
    "tzouras", "ud", "udu", "ugal",
    "umuduri", "unitar", "valiha",
    "veena", "verrophone",
    "waterphone", "whip", "willow flute",
    "xun", "xylorimba", "yoke lutes",
    "zhonghu", "bouzouki", "sanxian",
    "bock a da bock", "tambourine de bearne",
    "accordina", "adungu", "agogo", "agung",
    "akadinda", "alboka", "almglocken", "amadinda",
    "an bau", "an moi", "an tinh", "an tranh", "an ty ba",
    "andrews harp", "angélique", "ankle bells",
    "antara", "apollonikon", "archicembalo",
}


def normalize_for_lookup(name):
    """Normalize an instrument name for lookup in the sets above."""
    name = name.lower().strip()
    name = re.sub(r"[\(\)\[\]\"]", "", name)
    name = name.replace("_", " ").replace("-", " ").strip()
    name = re.sub(r"\s+", " ", name)
    return name


def get_instrument_flags(name):
    """Return (is_popular, is_uncommon) for a given instrument name string."""
    key = normalize_for_lookup(name)
    is_pop = key in POPULAR_INSTRUMENTS or any(
        key.startswith(p) or key.endswith(p) or p.startswith(key) or p.endswith(key)
        for p in POPULAR_INSTRUMENTS
    )
    is_un = key in UNCOMMON_INSTRUMENTS
    if is_pop and is_un:
        is_un = False
    return is_pop, is_un
